<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>UTowny</AssemblyName>
    <RootNamespace>UTowny</RootNamespace>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Version>1.0.0-rc.7</Version>
    <Description>Persistent towns, land protection, nations and consensual wars for OpenMod Unturned.</Description>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="tests/**/*.cs" />
    <EmbeddedResource Include="config.yaml" />
    <EmbeddedResource Include="translations.yaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OpenMod.Unturned" Version="3.8.10" />
    <PackageReference Include="OpenMod.Unturned.Redist" Version="3.26.1.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.10" />
  </ItemGroup>
</Project>
