<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>UTowny</AssemblyName>
    <RootNamespace>UTowny</RootNamespace>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="config.yaml" />
    <EmbeddedResource Include="translations.yaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OpenMod.Unturned" Version="3.8.10" />
    <PackageReference Include="OpenMod.Unturned.Redist" Version="3.26.1.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>
</Project>
