using Microsoft.Data.Sqlite;using Microsoft.Extensions.Options;using UTowny.Caching;using UTowny.Configuration;using UTowny.Domain.Claims;using UTowny.Domain.Common;using UTowny.Persistence.Database;using UTowny.Utilities;
namespace UTowny.Services;
public interface IClaimService { Claim? Get(GridCoord g); Task<Result<Claim>> ClaimAsync(PlayerId actor,GridCoord grid,bool bypassAdjacency=false,CancellationToken ct=default); int GetAllowance(TownId town); }
public sealed class ClaimService:IClaimService
{
 private readonly MutationGate m_Gate;

 private readonly IDatabaseConnectionFactory m_Db;private readonly IWorldStateCache m_Cache;private readonly IAuthorizationService m_Auth;private readonly IGridService m_Grid;private readonly IOptions<UTownyOptions> m_Options;private readonly KeyedLock<long> m_Lock=new();
 public ClaimService(IDatabaseConnectionFactory db,IWorldStateCache cache,IAuthorizationService auth,IGridService grid,IOptions<UTownyOptions> options,MutationGate gate){m_Gate=gate;m_Db=db;m_Cache=cache;m_Auth=auth;m_Grid=grid;m_Options=options;}
 public Claim? Get(GridCoord g)=>m_Cache.GetClaim(g);public int GetAllowance(TownId t)=>m_Options.Value.Towns.StartingClaims+(m_Cache.GetResidentCount(t)*m_Options.Value.Towns.ClaimsPerResident);
 public Task<Result<Claim>> ClaimAsync(PlayerId actor,GridCoord grid,bool bypassAdjacency=false,CancellationToken ct=default) => m_Gate.RunAsync(async () => {var m=m_Cache.GetMembership(actor);if(m is null)return Result<Claim>.Fail("not_in_town");if(!m_Auth.Can(actor,m.TownId,TownAction.Claim))return Result<Claim>.Fail("insufficient_role");using(await m_Lock.AcquireAsync(m.TownId.Value,ct)){if(m_Cache.GetClaim(grid)!=null)return Result<Claim>.Fail("claim_already_owned");var claims=m_Cache.GetTownClaims(m.TownId);if(claims.Count>=GetAllowance(m.TownId))return Result<Claim>.Fail("claim_limit");if(m_Options.Value.Claims.RequireAdjacency&&!bypassAdjacency&&claims.Count>0&&!claims.Any(c=>m_Grid.Touches(c.Grid,grid)))return Result<Claim>.Fail("claim_not_adjacent");await using var db=await m_Db.OpenAsync(ct);await using var tx=await db.BeginTransactionAsync(ct);await using(var spend=db.CreateCommand()){spend.Transaction=(SqliteTransaction)tx;spend.CommandText="UPDATE towns SET bank_balance=bank_balance-$cost WHERE id=$t AND bank_balance >= $cost";spend.Parameters.AddWithValue("$cost",m_Options.Value.Claims.ClaimPrice);spend.Parameters.AddWithValue("$t",m.TownId.Value);if(await spend.ExecuteNonQueryAsync(ct)!=1){await tx.RollbackAsync(ct);return Result<Claim>.Fail("insufficient_town_balance");}}try{long id;await using(var ins=db.CreateCommand()){ins.Transaction=(SqliteTransaction)tx;ins.CommandText="INSERT INTO claims(town_id,map_id,grid_x,grid_z,for_sale,price,protection_flags) VALUES($t,$m,$x,$z,0,0,0);SELECT last_insert_rowid();";ins.Parameters.AddWithValue("$t",m.TownId.Value);ins.Parameters.AddWithValue("$m",grid.MapId);ins.Parameters.AddWithValue("$x",grid.X);ins.Parameters.AddWithValue("$z",grid.Z);id=(long)(await ins.ExecuteScalarAsync(ct))!;}await tx.CommitAsync(ct);var c=new Claim(new(id),m.TownId,grid,null,false,0,0);m_Cache.UpsertClaim(c);var town=m_Cache.GetTown(m.TownId)!;m_Cache.UpsertTown(town with{BankBalance=town.BankBalance-m_Options.Value.Claims.ClaimPrice});return Result<Claim>.Ok(c);}catch(SqliteException ex)when(ex.SqliteErrorCode==19){await tx.RollbackAsync(ct);return Result<Claim>.Fail("claim_already_owned");}}}, ct);
}
