using Microsoft.Data.Sqlite;using Microsoft.Extensions.Options;using UTowny.Caching;using UTowny.Configuration;using UTowny.Domain.Claims;using UTowny.Domain.Common;using UTowny.Persistence.Database;using UTowny.Utilities;
namespace UTowny.Services;
public interface IPlotService { Task<Result<Claim>> SetForSaleAsync(PlayerId actor,GridCoord grid,long price,CancellationToken ct=default); Task<Result<Claim>> SetNotForSaleAsync(PlayerId actor,GridCoord grid,CancellationToken ct=default); Task<Result<Claim>> BuyAsync(PlayerId buyer,GridCoord grid,CancellationToken ct=default); }
public sealed class PlotService:IPlotService
{
 private readonly MutationGate m_Gate;

 private readonly IDatabaseConnectionFactory m_Db;private readonly IWorldStateCache m_Cache;private readonly IAuthorizationService m_Auth;private readonly IOptions<UTownyOptions> m_Options;private readonly KeyedLock<long> m_ClaimLock=new();
 public PlotService(IDatabaseConnectionFactory db,IWorldStateCache cache,IAuthorizationService auth,IOptions<UTownyOptions> options,MutationGate gate){m_Gate=gate;m_Db=db;m_Cache=cache;m_Auth=auth;m_Options=options;}
 public Task<Result<Claim>> SetForSaleAsync(PlayerId actor,GridCoord g,long price,CancellationToken ct=default) => m_Gate.RunAsync(async () => {if(price<0)return Result<Claim>.Fail("invalid_amount");var c=m_Cache.GetClaim(g);if(c is null)return Result<Claim>.Fail("plot_not_found");if(!m_Auth.Can(actor,c.TownId,TownAction.ManagePlot))return Result<Claim>.Fail("insufficient_role");using(await m_ClaimLock.AcquireAsync(c.Id.Value,ct)){await using var db=await m_Db.OpenAsync(ct);await using var cmd=db.CreateCommand();cmd.CommandText="UPDATE claims SET for_sale=1,price=$p WHERE id=$id AND plot_owner_steam64 IS NULL";cmd.Parameters.AddWithValue("$p",price);cmd.Parameters.AddWithValue("$id",c.Id.Value);if(await cmd.ExecuteNonQueryAsync(ct)!=1)return Result<Claim>.Fail("plot_already_owned");var n=c with{ForSale=true,Price=price};m_Cache.UpsertClaim(n);return Result<Claim>.Ok(n);}}, ct);
 public Task<Result<Claim>> SetNotForSaleAsync(PlayerId actor,GridCoord g,CancellationToken ct=default) => m_Gate.RunAsync(async () => {var c=m_Cache.GetClaim(g);if(c is null)return Result<Claim>.Fail("plot_not_found");if(!m_Auth.Can(actor,c.TownId,TownAction.ManagePlot))return Result<Claim>.Fail("insufficient_role");using(await m_ClaimLock.AcquireAsync(c.Id.Value,ct)){await using var db=await m_Db.OpenAsync(ct);await using var cmd=db.CreateCommand();cmd.CommandText="UPDATE claims SET for_sale=0,price=0 WHERE id=$id";cmd.Parameters.AddWithValue("$id",c.Id.Value);await cmd.ExecuteNonQueryAsync(ct);var n=c with{ForSale=false,Price=0};m_Cache.UpsertClaim(n);return Result<Claim>.Ok(n);}}, ct);
 public Task<Result<Claim>> BuyAsync(PlayerId buyer,GridCoord g,CancellationToken ct=default) => m_Gate.RunAsync(async () => {var c=m_Cache.GetClaim(g);if(c is null)return Result<Claim>.Fail("plot_not_found");using(await m_ClaimLock.AcquireAsync(c.Id.Value,ct)){c=m_Cache.GetClaim(g);if(c is null)return Result<Claim>.Fail("plot_not_found");if(!c.ForSale)return Result<Claim>.Fail("plot_not_for_sale");if(c.PlotOwner!=null)return Result<Claim>.Fail("plot_already_owned");var member=m_Cache.GetMembership(buyer);if(!m_Options.Value.Plots.OutsidersCanBuy&&(member is null||member.TownId!=c.TownId))return Result<Claim>.Fail("not_in_town");await using var db=await m_Db.OpenAsync(ct);await using var tx=await db.BeginTransactionAsync(ct);await using(var debit=db.CreateCommand()){debit.Transaction=(SqliteTransaction)tx;debit.CommandText="UPDATE players SET balance=balance-$p WHERE steam64=$b AND balance >= $p";debit.Parameters.AddWithValue("$p",c.Price);debit.Parameters.AddWithValue("$b",unchecked((long)buyer.Value));if(await debit.ExecuteNonQueryAsync(ct)!=1){await tx.RollbackAsync(ct);return Result<Claim>.Fail("insufficient_balance");}}await using(var claim=db.CreateCommand()){claim.Transaction=(SqliteTransaction)tx;claim.CommandText="UPDATE claims SET plot_owner_steam64=$b,for_sale=0,price=0 WHERE id=$id AND for_sale=1 AND plot_owner_steam64 IS NULL";claim.Parameters.AddWithValue("$b",unchecked((long)buyer.Value));claim.Parameters.AddWithValue("$id",c.Id.Value);if(await claim.ExecuteNonQueryAsync(ct)!=1){await tx.RollbackAsync(ct);return Result<Claim>.Fail("plot_state_changed");}}long townBal;await using(var town=db.CreateCommand()){town.Transaction=(SqliteTransaction)tx;town.CommandText="UPDATE towns SET bank_balance=bank_balance+$p WHERE id=$t RETURNING bank_balance";town.Parameters.AddWithValue("$p",c.Price);town.Parameters.AddWithValue("$t",c.TownId.Value);townBal=(long)(await town.ExecuteScalarAsync(ct))!;}await tx.CommitAsync(ct);var n=c with{PlotOwner=buyer,ForSale=false,Price=0};m_Cache.UpsertClaim(n);var t=m_Cache.GetTown(c.TownId)!;m_Cache.UpsertTown(t with{BankBalance=townBal});return Result<Claim>.Ok(n);}}, ct);
}
